[package]
name = "abstract-interface"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = "Abstract deployment helpers with cw-orchestrator"

[features]
default = ["integration"]
daemon = ["cw-orch/daemon"]
integration = []

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
semver = { workspace = true, default-features = false }
schemars = { workspace = true }
cw-controllers = { workspace = true }
thiserror = { workspace = true }
cw2 = { workspace = true }
cw-asset = { workspace = true }
abstract-core = { workspace = true, features = ["interface"] }

cw-orch = { workspace = true }
tokio = { workspace = true }
log = "0.4.14"
serde_json = "1.0.79"
speculoos = { workspace = true }

# Keep these here
module-factory = { package = "abstract-module-factory", path = "../../contracts/native/module-factory", default-features = false, version = "0.15.1" }
account-factory = { package = "abstract-account-factory", path = "../../contracts/native/account-factory", default-features = false, version = "0.15.1" }
ans-host = { package = "abstract-ans-host", path = "../../contracts/native/ans-host", default-features = false, version = "0.15.1" }
version-control = { package = "abstract-version-control", path = "../../contracts/native/version-control", default-features = false, version = "0.15.1" }
proxy = { package = "abstract-proxy", path = "../../contracts/account/proxy", default-features = false, version = "0.15.1" }
manager = { package = "abstract-manager", path = "../../contracts/account/manager", default-features = false, version = "0.15.1" }

[build-dependencies]
serde_json = "1.0.79"

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }
