[package]
name = "astroport"
version = "0.1.0"
authors = ["CyberHoward"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "0.16" }
cw20 = { version = "0.8" }
cosmwasm-bignumber = "2.2"
terra-cosmwasm = "2.2"
terraswap = "2.4.0"
cosmwasm-storage = { version = "0.16" }
cw-storage-plus = { version = "0.10" }
cw-controllers = { version = "0.8" }
cw2 = { version = "0.10" }
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26" }
pandora-os = { version = "0.1.0", path = "../../../../packages/pandora-os" }

[dev-dependencies]
cosmwasm-schema = { version = "0.16" }
cw-multi-test = { version = "0.8"}
terra-mocks = {git ="https://github.com/terra-money/cosmwasm-contracts.git", rev = "b25f4ac2d7bddaa3a18838cfe51d18e1ae855dcd", package = "terra-mocks"}
terra-multi-test = {git="https://github.com/astroport-fi/terra-plus", rev="b3991b9b109accf445fec086ce9792b197be6ca4", package = "terra-multi-test"}
cosmwasm-vm = { version = "0.16.0", default-features = false, features = ["iterator"] }

treasury = { version = "0.1.0", path = "../../../core/treasury" }
memory = { version = "0.1.0", path = "../../../native/memory" }
cw20-base = { version = "0.8", features = ["library"] }
astroport-factory = { version = "0.1.0", path = "../../../mocks/mock_astroport/astroport_factory" }
astroport-pair = { version = "0.1.0", path = "../../../mocks/mock_astroport/astroport_pair" }
astroport-token = { version = "0.1.0", path = "../../../mocks/mock_astroport/astroport_token" }
astroport = {git = "https://github.com/astroport-fi/astroport-core.git", branch = "master"}
