[package]
name = "manager"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}

exclude = [
  "contract.wasm",
  "hash.txt",
]


[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-controllers = {workspace = true}
cw-storage-plus = {workspace = true}
cw2 = {workspace = true}
cw20 = {workspace = true}
cw-asset= {workspace = true}
schemars = {workspace = true}
serde = {workspace = true}
thiserror = {workspace = true}
abstract-sdk = {workspace = true}
abstract-os = {workspace = true}
semver = {workspace = true}

[dev-dependencies]
cw-multi-test = { workspace = true }
cw20 = { workspace = true }
rstest = {workspace = true }
speculoos = {workspace = true } 

proxy = { path = "../proxy" }
ans-host = { path = "../../native/ans-host" }
os-factory = { path = "../../native/os-factory" }
module-factory = { path = "../../native/module-factory" }
version-control = { path = "../../native/version-control" }
