[package]
name = "manager"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-storage = {workspace = true}
cosmwasm-schema = { workspace = true }
cw-controllers = {workspace = true}
cw-storage-plus = {workspace = true}
cw2 = {workspace = true}
cw20 = {workspace = true}
cw-asset= {workspace = true}
schemars = {workspace = true}
serde = {workspace = true}
thiserror = {workspace = true}
abstract-sdk = {workspace = true}
abstract-os = {workspace = true}
protobuf = {workspace = true}
semver = {workspace = true}

[dev-dependencies]
cw-multi-test = { workspace = true }
cw20 = { workspace = true }

proxy = { path = "../proxy" }
ans_host = { path = "../../native/ans-host" }
os-factory = { path = "../../native/factory" }
module-factory = { path = "../../native/module_factory" }
version-control = { path = "../../native/version_control" }

rstest = "0.16.0"
speculoos = "0.11.0"


[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
          --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
            --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
              cosmwasm/rust-optimizer:0.12.5"""
store = """terra-rust code store test-owner ..\\..\\artifacts\\xxx.wasm"""
instantiate = """terra-rust code instantiate test-owner ..\\..\\artifacts\\xxx.wasm .\\pool_init.json --admin same"""
migrate = """terra-rust code migrate test-owner ..\\..\\artifacts\\xxx.wasm """
