[package]
name = "proxy"
version = "0.1.0"
authors = ["CyberHoward"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.0" }
cosmwasm-storage = { version = "1.0" }
cw-controllers = { version ="0.13" }
cw-storage-plus = "0.13"
cw2 = "0.13"
cw20 = { version = "0.13" }
cw-asset = "2.0"
abstract-os = { version = "0.1.0", path = "../../../packages/abstract" }
terraswap = "2.4.0"
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26" }
semver = "1"

[dev-dependencies]
cosmwasm-schema = { version = "1.0" }
cw20-base = { version = "0.13", features = ["library"] } 
cw-multi-test = { version = "0.13"}
