[package]
name = "abstract-proxy"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Abstract OS Proxy Contract"
license = { workspace = true }
readme = "README.md"
repository = "https://github.com/Abstract-OS/contracts"


exclude = [
  "contract.wasm",
  "hash.txt",
]


[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []


[dependencies]
abstract-os = { workspace = true }
abstract-sdk = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-asset = { workspace = true }
cw-controllers = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
schemars = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
abstract-macros = { workspace = true }

[dev-dependencies]
cw20 = { workspace = true }
rstest = { workspace = true }
speculoos = { workspace = true }
abstract-boot = { workspace = true }

