[package]
name = "abstract-boot"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = "Abstract deployment helpers with BOOT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
semver = { workspace = true, default-features = false }
schemars = { workspace = true }
cw-controllers = { workspace = true }
thiserror = { workspace = true }
cw2 = { workspace = true }
cw-asset = { workspace = true }
abstract-os = { workspace = true, features = ["boot"] }

boot-core = {  workspace = true  }
tokio = { version = "1.4", features = ["full"] }
secp256k1 = { version = "0.20.3", default-features = false }
log = "0.4.14"
anyhow = "1.0"
serde_json = "1.0.79"
reqwest = { version = "0.11.9" }
base64 = "0.13.0"
rust_decimal = "1.12.2"
rust_decimal_macros = "1.12.2"
cosmwasm-storage = "1.1"
sha256 = "1.0.3"
base16 = "0.2.1"
