[package]
name = "boot-abstract"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = "Abstract deployment helpers with BOOT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
semver = { workspace = true, default-features = false }
schemars = { workspace = true }
cw-controllers = { workspace = true }
thiserror = { workspace = true }
cw2 = { workspace = true }
cw-asset = { workspace = true }
abstract-sdk = { workspace = true }
abstract-os = { workspace = true }

boot-core = {  version = "0.1.1" ,git = "https://github.com/Abstract-OS/BOOT" }
protobuf = { version = "2", features = ["with-bytes"] }
tokio = { version = "1.4", features = ["full"] }
secp256k1 = { version = "0.20.3", default-features = false }
log = "0.4.14"
anyhow = "1.0"
serde_json = "1.0.79"
reqwest = { version = "0.11.9" }
dotenv = "0.15.0"
env_logger = "0.8.3"
base64 = "0.13.0"
rust_decimal = "1.12.2"
rust_decimal_macros = "1.12.2"
cw20 = { version = "0.15.0" }
cw20-base = { version = "0.15.0" }
cosmwasm-storage = "1.1"
sha256 = "1.0.3"
base16 = "0.2.1"
