[workspace]
members = [
    "packages/*",
    "contracts/native/*",
    "contracts/core/*",
    "contracts/testing",
    # "contracts/dapps/external/*",
    # "contracts/modules/apis/anchor",
    # "contracts/modules/apis/terraswap",
    "contracts/modules/add-ons/vault",
    "contracts/modules/add-ons/subscription",
    # "contracts/dapps/template",
    # "contracts/governance/token_weighted",
    # "contracts/perks/airdrop",
    # "contracts/services/*"
]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false