[workspace]
members = [
    "packages/*", 
    "contracts/gov",
    "contracts/bluna-vault",
    "contracts/community-fund",
    "contracts/profit-check",
    "contracts/stablecoin-peg-arb",
    "contracts/stablecoin-vault",
    "contracts/terraswap-wrapper",
    "contracts/vesting",
    "contracts/war-chest"
]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
