[workspace]
members = [
    "packages/*",
    "contracts/version_control",
    "contracts/core/*",
    # "contracts/dapps/external/*",
    "contracts/dapps/external/anchor",
    "contracts/dapps/external/terraswap",
    "contracts/dapps/internal/vault"
    # "contracts/dapps/template",
    # "contracts/governance/token_weighted",
    # "contracts/perks/airdrop",
    # "contracts/services/*"
]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
