[workspace]
members = [
    "packages/*",
    "contracts/native/*",
    "contracts/core/*",
    "contracts/testing",
    "contracts/token",
    "contracts/modules/apps/etf",
    "contracts/modules/apps/subscription",
    "contracts/modules/extensions/tendermint-staking",
    "contracts/modules/extensions/dex",
    "contracts/modules/perks/vesting",
    "contracts/ibc-hosts/osmosis",
    "scripts"
]

[workspace.package]
version = "0.2.0-beta.7"
authors = ["CyberHoward <cyberhoward@protonmail.com>", "Riada <riada@abstract.money>", "Abstract Money <contact@abstract.money>"]
edition = "2021"
homepage = "https://abstract.money"
documentation = "https://docs.abstract.money/"
repository = "https://github.com/Abstract-OS/contracts"
license = "GPL-3.0-or-later"
keywords = ["cosmos", "cosmwasm", "framework"]

[workspace.dependencies]
cosmwasm-std = { version = "1.1" }
cosmwasm-storage = { version = "1.1" }
cosmwasm-schema = { version = "1.1" }
cw-controllers = { version = "0.16" }
cw-utils = { version = "0.16" }
cw-storage-plus = "0.16"
cw2 = { version = "0.16" }
cw20 = { version = "0.16" }
cw20-base = { version = "0.16", features = ["library"] }
cw-asset = { version = "2.2" }
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
protobuf = { version = "2", features = ["with-bytes"] }
semver = {version = "1.0", git = "https://github.com/Abstract-OS/semver.git"}

boot-core = {version = "0.2.0", git =  "https://github.com/Abstract-OS/BOOT.git"}

abstract-sdk = { version = "0.2.0-beta.7", path = "packages/abstract-sdk" }
abstract-os = { version = "0.2.0-beta.7", path = "packages/abstract-os" }
abstract-app = { version = "0.2.0-beta.7", path = "packages/abstract-app", features = ["library"] }
abstract-extension = { version = "0.2.0-beta.7", path = "packages/abstract-extension", features = ["library"] }
abstract-ibc-host = { version = "0.2.0-beta.7", path = "packages/abstract-ibc-host" }
abstract-ica = { version = "0.2.0-beta.7", path = "packages/abstract-ica" }

cw-multi-test = { git = "https://github.com/Abstract-OS/cw-plus.git", branch = "main" }

[workspace.dev-dependencies]
rstest = "0.16.0"


[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
