[workspace]
members = ["packages/*", "contracts/native/*", "contracts/account/*", "scripts"]

# Enable the version 2 feature resolver, which avoids unifying features for targets that are not being built
#
# Critically this prevents dev-dependencies from enabling features even when not building a target that
# uses dev-dependencies, e.g. the library crate. This in turn ensures that we can catch invalid feature
# flag combinations that would otherwise only surface in dependent crates
#
# Reference - https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2
# See - https://github.com/apache/arrow-rs/pull/1822/files
resolver = "2"

[workspace.package]
version = "0.15.0"
authors = [
  "CyberHoward <cyberhoward@protonmail.com>",
  "Riada <riada@abstract.money>",
  "Abstract Money <contact@abstract.money>",
]
edition = "2021"
homepage = "https://abstract.money"
documentation = "https://docs.abstract.money/"
repository = "https://github.com/AbstractSDK/contracts"
license = "GPL-3.0-or-later"
keywords = ["cosmos", "cosmwasm", "framework"]

[workspace.dependencies]
cosmwasm-std = { version = "1.2" }
cosmwasm-schema = { version = "1.2" }
cw-controllers = { version = "1.0" }
cw-utils = { version = "1.0" }
cw-storage-plus = "1.0"
cw2 = { version = "1.0" }
cw20 = { version = "1.0" }
cw20-base = { version = "1.0", features = ["library"] }

cw-asset = { version = "3.0" }
cw-ownable = { version = "0.5" }
cw-address-like = { version = "1.0" }

schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
protobuf = { version = "2", features = ["with-bytes"] }

clap = { version = "4.0.32", features = ["derive"] }
semver = "1.0"
cw-semver = { version = "1.0" }
cw-orch = { version = "0.12" }
tokio = { version = "1.4", features = ["full"] }

## crates in order of publishing ## see docs/Publishing.md

abstract-adapter = { path = "packages/abstract-adapter" }
abstract-app = { path = "packages/abstract-app" }

# Keep these as path, creates cirular dependency otherwise
# Only need to re-publish all contracts if a re-publish of abstract-interface is required
abstract-interface = { path = "packages/abstract-interface" }
module-factory = { package = "abstract-module-factory", path = "contracts/native/module-factory" }
account-factory = { package = "abstract-account-factory", path = "contracts/native/account-factory" }
ans-host = { package = "abstract-ans-host", path = "contracts/native/ans-host" }
version-control = { package = "abstract-version-control", path = "contracts/native/version-control" }
proxy = { package = "abstract-proxy", path = "contracts/account/proxy" }
manager = { package = "abstract-manager", path = "contracts/account/manager" }

abstract-sdk = { version = "0.15.0", path = "packages/abstract-sdk" }
abstract-testing = { version = "0.15.0", path = "packages/abstract-testing" }
abstract-core = { version = "0.15.0", path = "packages/abstract-core" }

# These should remain fixed and don't need to be re-published (unless changes are made)
abstract-macros = { version = "0.15.0", path = "packages/abstract-macros" }
abstract-ica = { version = "0.15.0", path = "packages/abstract-ica" }

## Testing
cw-multi-test = { version = "0.16.2" }
rstest = "0.17.0"
speculoos = "0.11.0"
anyhow = "1"

# Backup release profile, will result in warnings during optimization
[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
