[package]
name = "pandora-os"
version = "0.1.0"
authors = ["CyberHoward"]
edition = "2018"
description = "Helpers for pandora contracts"
license = "GPL-2.0-or-later"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
terra-cosmwasm = { version = "2.2.0" }
cosmwasm-bignumber = "2.2"
cosmwasm-std = { version = "0.16", features = ["iterator"] }
cosmwasm-storage = { version = "0.16", features = ["iterator"] }
cw-controllers = { version = "0.8" }
cw-storage-plus = { version = "0.8" }
cw2 = { version = "0.8" }
cw20 = { version = "0.8" }
cw20-base = { version = "0.8", features = ["library"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terraswap = "2.4.0"
thiserror = { version = "1.0.26" }
terra-rust-script-derive = {git = "https://github.com/CyberHoward/terra-rust-script-derive.git"}