[package]
name = "whale-airdrop"
version = "0.1.0"
authors = ["_astromartian"]
edition = "2018"
description = "Contract to facilitate WHALE Token airdrop"


exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
abstract-os = { version = "0.1.0" }

cosmwasm-std = { version = "1.0" }
cw-storage-plus = { version = "0.13.0" }
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
cw20 = { version = "0.13" }
cw20-base = { version = "0.13", features = ["library"] }
schemars = "0.8.3"
cosmwasm-bignumber = "2.2.0"

hex = "0.4.3"
sha3 = "0.13"

[dev-dependencies]
cosmwasm-schema = { version = "1.0" }
cosmwasm-storage = { version = "1.0" }
cw-multi-test =  { version = "0.13.0" } 