[package]
name = "subscription"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}

exclude = [
  "contract.wasm",
  "hash.txt",
]


[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true }
cw-controllers = {workspace = true}
cw-storage-plus = {workspace = true}
cosmwasm-schema = { workspace = true }
cw2 = {workspace = true}
cw20 = {workspace = true}
schemars = {workspace = true}
serde = {workspace = true}
thiserror = {workspace = true}
cw-asset= {workspace = true}
semver = {workspace = true}

abstract-sdk = {workspace = true}
abstract-app = {workspace = true}
abstract-os = {workspace = true}

[dev-dependencies]
cw-multi-test = {workspace = true}
cw20 = {workspace = true}
proxy = {path = "../../../core/proxy" }
