[package]
name = "abstract-osmosis-adapter"
version = "0.15.2"
authors = ["Abstract Money <contact@abstract.money>"]
edition = "2021"
description = "Abstract DexCommand implementation for Osmosis"
license = "MIT OR Apache-2.0"

[features]
default = ["full_integration"]
full_integration = ["dep:cw20", "dep:abstract-sdk", "dep:cw-asset", "dep:cw-utils", "dep:osmosis-std"]

[dependencies]
cosmwasm-std = { version = "1.1.2", features = ["stargate"] }
abstract-core = { version="0.16.1" }
abstract-staking-adapter-traits = { path = "../../../../adapter-packages/staking" }
abstract-dex-adapter-traits = { path = "../../../../adapter-packages/dex" }

#Abstract dependencies 
cw20 = { version = "0.15", optional = true }
abstract-sdk = { version="0.16.1", optional = true }
cw-asset = { version = "3.0.0", optional = true }
cw-utils = { version = "1.0.1", optional = true }
osmosis-std = { path = "../osmosis-std/", optional = true }


[dev-dependencies]
abstract-osmosis-adapter = {path=".", features=["full_integration"]}
cw-orch = { git="https://github.com/AbstractSDK/cw-orchestrator", branch="update/add-osmosis-test-tube", features=["test-tube"]}