[package]
name = "abstract-api"
version = "0.1.0"
edition = "2021"
description = "base API contract implementation"
license = "GPL-2.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [lib]
# crate-type = ["cdylib", "rlib"]


[features]
default = []
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# # use library feature to disable all instantiate/execute/query exports
library = []
# ibc = ["dep:simple-ica","abstract-os/ibc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.1" }
cw-storage-plus = { version = "0.14" }
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
schemars = "0.8.3"
cw-controllers = { version = "0.14" }
thiserror = { version = "1.0.21" }
cw2 = "0.14"
abstract-sdk = { version = "0.1.0", path = "../abstract-sdk" }
abstract-os = {version = "0.1.0", path = "../abstract-os"}

# Ibc deps
simple-ica = {path = "../simple-ica"}