[package]
name = "abstract-api"
version = { workspace = true }
authors = {workspace = true}
edition = {workspace = true}
license = { workspace = true }
description = "base api contract implementation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [lib]
# crate-type = ["cdylib", "rlib"]


[features]
default = []
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# # use library feature to disable all instantiate/execute/query exports
library = []
# ibc = ["dep:abstract-ica","abstract-os = {workspace = true}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = {workspace = true}
cw-storage-plus = {workspace = true}
serde = {workspace = true}
schemars = {workspace = true}
cw-controllers = {workspace = true}
thiserror = {workspace = true}
cw2 = {workspace = true}
abstract-sdk = {workspace = true}
abstract-os = {workspace = true}
