[package]
name = "osmosis-host"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}

exclude = [
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version =  "1.1", features = ["stargate"]}
thiserror = {workspace = true}
dex = { path = "../../modules/apis/dex", features = ["osmosis", "library"] }
abstract-os = { workspace = true }
abstract-ibc-host = { workspace = true}
abstract-sdk = {workspace = true}
cosmwasm-schema = { workspace = true }
