[package]
name = "anchor"
version = "0.1.0"
authors = ["CyberHoward"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "0.16" }
cw20 = { version = "0.9.1" }
terra-cosmwasm = "2.2"
terraswap = "2.4.0"
# cosmwasm-storage = { version = "0.16" }
cw-storage-plus = { version = "0.9.1" }
cw-controllers = { version = "0.9.1" }
cw2 = { version = "0.9.1" }
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26" }
pandora-os = { version = "0.1.0", path = "../../../../packages/pandora-os" }
pandora-dapp-base = { version = "0.1.0", path = "../../../pandora_dapp_base", features = ["library"] }

[dev-dependencies]
cosmwasm-schema = { version = "0.16" }
