[package]
name = "abstract-astroport-adapter"
version = "2.10.0"
authors = ["Abstract Money <contact@abstract.money>"]
edition = "2021"
description = "Abstract DexCommand implementation for Astroport"
license = "Apache-2.0"
repository = "https://github.com/astroport-fi/astroport"

[features]
default = ["full_integration"]
local = []
full_integration = [
  "dep:cw20",
  "dep:cosmwasm-schema",
  "dep:cw-asset",
  "dep:cw-utils",
  "dep:astroport",
]

[dependencies]
cosmwasm-std = { version = "1.1" }
abstract-staking-adapter-traits = { path = "../../../../adapters/packages/staking" }
abstract-dex-adapter-traits = { path = "../../../../adapters/packages/dex" }
abstract-sdk = { path = "../../../../framework/packages/abstract-sdk" }


cw20 = { version = "0.15", optional = true }
cosmwasm-schema = { version = "1.1", optional = true }
cw-asset = { version = "3.0.0", optional = true }
cw-utils = { version = "1.0.1", optional = true }

astroport = { path = "../astroport/", optional = true }

[dev-dependencies]
abstract-dex-adapter-traits = { path = "../../../../adapters/packages/dex", features = [
  "testing",
] }
cw-orch = { version = "0.13.1", features = ["daemon"] }
ibc-chain-registry = "0.24.1"
