[package]
name = "os-factory"
version = "0.1.0"
authors = ["CyberHoward"]
edition = "2018"
description = "A CosmWasm DAO factory contract - Generates the initial DAO infrastructure"
license = "MIT"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.0" }
cw-controllers = { version ="0.13" }
cw-storage-plus = "0.13"
cw2 = "0.13"
cw20 = "0.13"
abstract-os = { version = "0.1.0", path = "../../../packages/abstract" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.21" }
protobuf = { version = "2", features = ["with-bytes"] }
cw-asset = {version = "2.0"}

[dev-dependencies]
cosmwasm-schema = "1.0"
cosmwasm-storage = { version = "1.0" }
