[package]
name = "vault-dapp"
version = "0.1.0"
authors = ["CyberHoward"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "0.16.7" }
cw-controllers = { version = "0.9.1" }
cw-storage-plus = "0.9.1"
cw2 = "0.9.1"
cw20 = { version = "0.9.1" }
cw20-base = { version = "0.9.1", features = ["library"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terra-cosmwasm = "2.2"
thiserror = { version = "1.0.21" }
abstract-os = { version = "0.1.0", path = "../../../../packages/abstract" }
abstract-add-on = { version = "0.1.0", path = "../../../../packages/abstract_add_on", features = ["library"] }
protobuf = { version = "2", features = ["with-bytes"] }
cw-asset = "1.0.2"
semver = "1.0.0"


[dev-dependencies]
memory = { version = "0.1.0", path = "../../../native/memory" }
terraswap = "2.4.0"
cosmwasm-schema = { version = "0.16" }
cw-multi-test = { version = "0.9.1" }
terra-mocks = { git = "https://github.com/terra-money/cosmwasm-contracts.git", rev = "b25f4ac2d7bddaa3a18838cfe51d18e1ae855dcd", package = "terra-mocks" }
terra-multi-test = { git = "https://github.com/astroport-fi/terra-plus", rev = "b3991b9b109accf445fec086ce9792b197be6ca4", package = "terra-multi-test" }
cw20-base = { version = "0.9.1", features = ["library"] }
proxy = { version = "0.1.0", path = "../../../core/proxy" }
terraswap-factory = { version = "0.1.0", path = "../../../mocks/mock_terraswap/terraswap_factory" }
terraswap-pair = { version = "0.1.0", path = "../../../mocks/mock_terraswap/terraswap_pair" }
terraswap-token = { version = "0.1.0", path = "../../../mocks/mock_terraswap/terraswap_token" }
