[package]
name = "abstract-version-control"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Abstract Version Control Contract"
license = { workspace = true }
readme = "README.md"
repository = "https://github.com/Abstract-OS/contracts"

exclude = ["contract.wasm", "hash.txt"]


[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["export"]
export = []


[dependencies]
cosmwasm-std = { workspace = true }
cw-controllers = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cw-semver = { workspace = true }
abstract-sdk = { workspace = true }
abstract-core = { workspace = true }
abstract-macros = { workspace = true }
cw-ownable = { workspace = true }


[dev-dependencies]
cosmwasm-schema = { workspace = true }
abstract-boot = { workspace = true }
boot-core = { workspace = true }
anyhow = { workspace = true }
module-factory = { workspace = true }
account-factory = { workspace = true }
ans-host = { workspace = true }
proxy = { workspace = true }
manager = { workspace = true }
speculoos = { workspace = true }
abstract-testing = { workspace = true }

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
