[package]
name = "pandora-vesting"
version = "0.1.0"
authors = ["Terraform Labs, PTE."]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
pandora = { version = "0.1.0", path = "../../../packages/pandora" }

cosmwasm-std = { version = "0.16", features = ["iterator"] }
cw-storage-plus = "0.8.0"
cw20 = { version = "0.8" }

schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "0.16", default-features = false  }
cw-multi-test = "0.8.0"
cw20-base = { version = "0.8", features = ["library"] }