[package]
name = "module-factory"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
description = ""
license = "MIT"

exclude = [
  "contract.wasm",
  "hash.txt",
]


[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []
# for quicker tests, cargo test --lib
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true }
cw-controllers = {workspace = true}
cosmwasm-schema = { workspace = true }
cw-storage-plus = {workspace = true}
cw2 = {workspace = true}
thiserror = {workspace = true}
semver = {workspace = true}
protobuf = {workspace = true}
abstract-sdk = {workspace = true}
abstract-os = {workspace = true}
