[package]
name = "subscription"
version = "0.1.0-rc.1"
authors = ["CyberHoward <cyberhoward@users.noreply.github.com>"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.0" }
cw-controllers = { version = "0.13" }
cw-storage-plus = "0.13"
cw2 = "0.13"
cw20 = { version = "0.13" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.21" }
protobuf = { version = "2", features = ["with-bytes"] }
cw-asset = {version = "2.2.0"}
semver = "1.0.0"

abstract-sdk = { path = "../../../../packages/abstract-sdk" }
abstract-add-on = { path = "../../../../packages/abstract-add-on", features = ["library"] }
abstract-os = { path = "../../../../packages/abstract-os" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0" }
cw-multi-test = { version = "0.13" }
cw20-base = { version = "0.13", features = ["library"] }
proxy = { version = "0.1.0-rc.1", path = "../../../core/proxy" }