[package]
name = "version-control"
version = "0.1.0"
authors = ["White Whale"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "0.16.7" }
cw-controllers = { version ="0.9.1" }
cw-storage-plus = "0.9.1"
cw2 = "0.9.1"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terra-cosmwasm = "2.2"
terraswap = "2.4.0"
thiserror = { version = "1.0.21" }
abstract-os = { version = "0.1.0", path = "../../../packages/abstract" }
semver = "1"


[dev-dependencies]
cosmwasm-schema = { version = "0.16" }
