[package]
name = "abstract-sdk"
version = "0.1.0-rc.1"
authors = ["CyberHoward <cyberhoward@users.noreply.github.com>"]
edition = "2021"
description = "Helpers for Abstract contracts"
license = "GPL-2.0-or-later"
readme = "README.md"
repository = "https://github.com/Abstract-OS/contracts/tree/main/packages/abstract-sdk"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.0", features = ["iterator", "staking"] }
cosmwasm-storage = { version = "1.0", features = ["iterator"] }
cw-controllers = { version = "0.13" }
cw-storage-plus = { version = "0.13" }
cw2 = { version = "0.13" }
cw20 = { version = "0.13" }
cw20-base = { version = "0.13", features = ["library"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26" }
cw-asset = {version = "2.2.0"}
serde-cw-value = "0.7.0"
abstract-os = {path = "../abstract-os", version = "0.1.0-rc.1"}
# abstract-os = {path = "../abstract-os"}
