[package]
name = "abstract-sdk"
version = "0.1.0"
authors = ["CyberHoward"]
edition = "2018"
description = "Helpers for Abstract contracts"
license = "GPL-2.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.0", features = ["iterator"] }
cosmwasm-storage = { version = "1.0", features = ["iterator"] }
cw-controllers = { version = "0.13" }
cw-storage-plus = { version = "0.13" }
cw2 = { version = "0.13" }
cw20 = { version = "0.13" }
cw20-base = { version = "0.13", features = ["library"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26" }
cw-asset = {version = "2.2.0"}
serde-cw-value = "0.7.0"
abstract-os = {path = "../abstract-os"}
