[package]
name = "abstract-ica"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = "Abstract ICA struct and protocol version definitions"

[features]
default = []


[dependencies]
cosmwasm-std = { workspace = true, features = ["ibc3"] }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cosmwasm-schema = { workspace = true }

[dev-dependencies]
speculoos = { workspace = true }
