[package]
name = "white-whale"
version = "1.0.0"
authors = ["White Whale"]
edition = "2018"
description = "Common helpers for other white whale"
license = "Apache-2.0"
repository = "https://github.com/White-Whale-DeFi-Platform/contracts"
homepage = "https://whitewhale.finance"
documentation = "https://whitewhale.finance"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
terra-cosmwasm = { version = "2.2.0" }
cosmwasm-bignumber = "2.2"
cosmwasm-std = { version = "0.16", features = ["iterator"] }
cosmwasm-storage = { version = "0.16", features = ["iterator"] }
cw-storage-plus = { version = "0.8" }
cw20 = { version = "0.8" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terraswap = "2.4.0"
thiserror = { version = "1.0.26" }