[package]
name = "dex"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}

exclude = [
  "contract.wasm",
  "hash.txt",
]


[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["juno"]
library = []
backtraces = ["cosmwasm-std/backtraces"]
juno = ["dep:wasmswap", "dep:cw20_junoswap", "dep:terraswap"]
terra = ["dep:terraswap"]
osmosis = ["library", "dep:osmosis-std"]
all = ["terra", "juno", "osmosis"]

# Keep as is until TendermintStake updates.
[dependencies]
cosmwasm-std = {workspace = true}
schemars = {workspace = true}
serde = {workspace = true}
thiserror = {workspace = true}
abstract-os = {workspace = true}
abstract-sdk = { workspace = true }
abstract-api = { workspace = true }
cw-asset = { workspace = true }

# Juno dexes
cw20_junoswap = {package = "cw20", version = "0.10.0", optional = true}
wasmswap = {git = "https://github.com/Wasmswap/wasmswap-contracts", tag = "v1.2.0", features = ["library"], optional = true}
# terraswap_juno = {package = "terraswap", version = "2.8.0", optional = true}

# Terra dexes
terraswap = { version = "2.8.0", optional = true }
cw20 = { workspace = true }

# Osmosis
osmosis-std = { version = "0.13.2", optional = true }

[dev-dependencies]
cosmwasm-schema = { workspace = true }
abstract-boot = { workspace = true }
boot-core = { workspace = true }
tokio = { version = "1.4", features = ["full"] }
semver = { workspace = true }
anyhow = { workspace = true }
dotenv = "0.15.0"
env_logger = "0.10.0"
abstract-api = { workspace = true, features = ["schema"] }
