[package]
name = "abstract-account-factory"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Abstract Factory Contract"
license = { workspace = true }
readme = "README.md"
repository = "https://github.com/AbstractSDK/contracts"

exclude = ["contract.wasm", "hash.txt"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["export"]
export = []

[dependencies]
abstract-core = { workspace = true }
abstract-sdk = { workspace = true }
abstract-macros = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-asset = { workspace = true }
cw-controllers = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
protobuf = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cw-ownable = { workspace = true }

[dev-dependencies]
abstract-boot = { workspace = true }
boot-core = { workspace = true }
anyhow = { workspace = true }
module-factory = { workspace = true }
ans-host = { workspace = true }
version-control = { workspace = true }
proxy = { workspace = true }
manager = { workspace = true }
speculoos = { workspace = true }
abstract-testing = { workspace = true }

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
