[package]
name = "treasury"
version = "0.1.0"
authors = ["White Whale"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { version = "0.16.2" }
cosmwasm-storage = { version = "0.16.0" }
cw-storage-plus = "0.8.0"
cw2 = "0.8.1"
cw20 = { version = "0.8" }
terraswap = "2.4.0"
cw-controllers = { version = "0.8" }
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
pandora = { version = "0.1.0", path = "../../../packages/pandora" }
thiserror = { version = "1.0.26" }
semver = "1"

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }
cw20-base = { version = "0.8", features = ["library"] } 
cw-multi-test = { version = "0.8"}
