[package]
name = "cw20-vesting"
version = "0.1.0"
authors = ["CyberHoward <cyberhoward@users.noreply.github.com>"]
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
abstract-os = { version = "0.1.0", path = "../../../../packages/abstract-os" }

cosmwasm-std = { version = "1.1", features = ["iterator"] }
cw-storage-plus = "0.14"
cw20 = { version = "0.14" }
cw2 = "0.14"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0", default-features = false  }
cw-multi-test = "0.14"
cw20-base = { version = "0.14", features = ["library"] }
