[package]
name = "tendermint-staking"
version = "0.1.0-rc.2"
authors = ["CyberHoward <cyberhoward@users.noreply.github.com>"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

# Keep as is until TendermintStake updates.
[dependencies]
cosmwasm-schema = { version = "1.1" }
cosmwasm-std = "1.1"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.21" }
abstract-os = { version = "0.1.0-rc.1", path = "../../../../packages/abstract-os" }
abstract-sdk = { version = "0.1.0-rc.1", path = "../../../../packages/abstract-sdk" }
abstract-api = { version = "0.1.0-rc.1", path = "../../../../packages/abstract-api", features = ["library"] }
