name:                           coverage

on:                             [push]

env: 
  CODECOV_TOKEN: 7f09ca79-34d7-4a5a-b6fd-b3b477a7b2e9

jobs:
  check_changes:
    name: Check for Rust changes
    runs-on: self-hosted
    container:
      image: rust:latest
    outputs:
      rust_changes: ${{ steps.rust_changes.outputs.rust_changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if any rust files have changed
        id: changes
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.rs
            Cargo.toml
            Cargo.lock
      - name: Check if any rust files have changed
        if: steps.changes.outputs.any_changed == 'true'
        id: rust_changes
        run: |
          echo "Rust files have changed"
          echo "rust_changes=true" >> $GITHUB_OUTPUT
  test:
    name: coverage
    if: ${{ needs.check-changes.outputs.rust-changes == 'true' }}
    runs-on: self-hosted
    needs: check_changes
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --workspace --timeout 120 --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
