[package]
name = "abstract-testing"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Abstract contract interfaces and storage layouts"
license = { workspace = true }
readme = "README.md"
repository = "https://github.com/Abstract-OS/contracts"


[dependencies]
cosmwasm-std = { workspace = true, features = ["iterator"] }
schemars = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
derive_builder = "0.12.0"
abstract-core = { workspace = true }
cosmwasm-schema = { workspace = true }
speculoos = { workspace = true }
serde_json = "1.0.79"
cw2 = { workspace = true }
cw-asset = { workspace = true }

[dev-dependencies]
abstract-sdk = { path = "../abstract-sdk", features = ["test-utils"] }
